FROM ghcr.io/thindil/gnat
COPY . /app
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
 && apt-get update && apt-get install -y \
 tcl-dev \
 tk-dev \
 && cd /app \
 && tclsh scripts/setup.tcl auto \
 && gprbuild -P tashy2.gpr \
 && gprinstall -P tashy2.gpr -p -XLIBRARY_TYPE=static --build-var=LIBRARY_TYPE --build-name=static \
 && cd .. \
 && rm -rf /app \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
