-- Copyright (c) 2021 Bartek thindil Jasicki <thindil@laeran.pl>
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

package Tk.Colors is

   --## rule off REDUCEABLE_SCOPE
   --## rule off NAMING_CONVENTION
   type Colors_Names is
     (ALICE_BLUE, ANTIQUE_WHITE, ANTIQUE_WHITE1, ANTIQUE_WHITE2,
      ANTIQUE_WHITE3, ANTIQUE_WHITE4, AQUA, AQUAMARINE, AQUAMARINE1,
      AQUAMARINE2, AQUAMARINE3, AQUAMARINE4, AZURE, AZURE1, AZURE2, AZURE3,
      AZURE4, BEIGE, BISQUE, BISQUE1, BISQUE2, BISQUE3, BISQUE4, BLACK,
      BLANCHED_ALMOND, BLUE, BLUE_VIOLET, BLUE1, BLUE2, BLUE3, BLUE4, BROWN,
      BROWN1, BROWN2, BROWN3, BROWN4, BURLYWOOD, BURLYWOOD1, BURLYWOOD2,
      BURLYWOOD3, BURLYWOOD4, CADET_BLUE, CADET_BLUE1, CADET_BLUE2,
      CADET_BLUE3, CADET_BLUE4, CHARTREUSE, CHARTREUSE1, CHARTREUSE2,
      CHARTREUSE3, CHARTREUSE4, CHOCOLATE, CHOCOLATE1, CHOCOLATE2, CHOCOLATE3,
      CHOCOLATE4, CORAL, CORAL1, CORAL2, CORAL3, CORAL4, CORNFLOWER_BLUE,
      CORNSILK, CORNSILK1, CORNSILK2, CORNSILK3, CORNSILK4, CRYMSON, CYAN,
      CYAN1, CYAN2, CYAN3, CYAN4, DARK_BLUE, DARK_CYAN, DARK_GOLDENROD,
      DARK_GOLDENROD1, DARK_GOLDENROD2, DARK_GOLDENROD3, DARK_GOLDENROD4,
      DARK_GRAY, DARK_GREEN, DARK_GREY, DARK_MAGENTA, DARK_OLIVE_GREEN,
      DARK_OLIVE_GREEN1, DARK_OLIVE_GREEN2, DARK_OLIVE_GREEN3,
      DARK_OLIVE_GREEN4, DARK_ORANGE, DARK_ORANGE1, DARK_ORANGE2, DARK_ORANGE3,
      DARK_ORANGE4, DARK_ORCHID, DARK_ORCHID1, DARK_ORCHID2, DARK_ORCHID3,
      DARK_ORCHID4, DARK_RED, DARK_SALMON, DARK_SEA_GREEN, DARK_SEA_GREEN1,
      DARK_SEA_GREEN2, DARK_SEA_GREEN3, DARK_SEA_GREEN4, DARK_SLATE_BLUE,
      DARK_SLATE_GRAY, DARK_SLATE_GRAY1, DARK_SLATE_GRAY2, DARK_SLATE_GRAY3,
      DARK_SLATE_GRAY4, DARK_SLATE_GREY, DARK_TURQUOISE, DARK_VIOLET,
      DEEP_PINK, DEEP_PINK1, DEEP_PINK2, DEEP_PINK3, DEEP_PINK4, DEEP_SKY_BLUE,
      DEEP_SKY_BLUE1, DEEP_SKY_BLUE2, DEEP_SKY_BLUE3, DEEP_SKY_BLUE4, DIM_GRAY,
      DIM_GREY, DODGER_BLUE, DODGER_BLUE1, DODGER_BLUE2, DODGER_BLUE3,
      DODGER_BLUE4, FIREBRICK, FIREBRICK1, FIREBRICK2, FIREBRICK3, FIREBRICK4,
      FLORAL_WHITE, FOREST_GREEN, FUCHSIA, GAINSBORO, GHOST_WHITE, GOLD, GOLD1,
      GOLD2, GOLD3, GOLD4, GOLDENROD, GOLDENROD1, GOLDENROD2, GOLDENROD3,
      GOLDENROD4, GRAY, GRAY0, GRAY1, GRAY2, GRAY3, GRAY4, GRAY5, GRAY6, GRAY7,
      GRAY8, GRAY9, GRAY10, GRAY11, GRAY12, GRAY13, GRAY14, GRAY15, GRAY16,
      GRAY17, GRAY18, GRAY19, GRAY20, GRAY21, GRAY22, GRAY23, GRAY24, GRAY25,
      GRAY26, GRAY27, GRAY28, GRAY29, GRAY30, GRAY31, GRAY32, GRAY33, GRAY34,
      GRAY35, GRAY36, GRAY37, GRAY38, GRAY39, GRAY40, GRAY41, GRAY42, GRAY43,
      GRAY44, GRAY45, GRAY46, GRAY47, GRAY48, GRAY49, GRAY50);
   --## rule on NAMING_CONVENTION
   --## rule on REDUCEABLE_SCOPE

end Tk.Colors;
