name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up the library
      run: scripts/setup.tcl auto

    - name: Style check
      run: |
         gprbuild -P tashy2.gpr
         gprclean -P tashy2.gpr

    - name: Generate the tests
      run: gnattest -P tashy2.gpr

    - name: Build and run the tests
      run: scripts/tests.tcl
