name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate the tests
      run: |
         scripts/setup.tcl auto
         gnattest -P tashy2.gpr

    - name: Build the tests
      run: gprbuild -P tests/driver/test_driver.gpr

    - name: Run the test
      run: |
         cd tests/driver
         ./test_runner
