name: AdaControl checks

on:
  push:
    branches: [ main ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adacontrol:9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up the library
      run: scripts/setup.tcl auto

    - name: Run AdaControl
      run: |
         mkdir obj
         scripts/check.tcl

    - name: Upload the log
      uses: actions/upload-artifact@v2
      if: failure()
      with:
         name: adacontrol.log
         path: adacontrol.log

